Update node to version 20
shiftcode/github-action-skip pull request #24
Opened 2024-04-02 08:04 UTC by vitaliibendyk

Add .nvmrc, update node 20.11

2024-04-02 14:45 UTC, michaelwittwer requested changes

2024-04-02 14:45 UTC, michaelwittwer commented on dist/package.json
this is should be ignored by `.gitignore`, why is it here?

2024-04-02 14:51 UTC, vitaliibendyk commented on dist/package.json
I haven't added it and also I tried to remove that, but despite that, it's still here.

2024-04-03 06:59 UTC, michaelwittwer approved these changes
When you merge the PR and the build was successful you can follow the instructions in the README file to create a new release by adding the git tag. Also the information about doing versioning without the `v...` was wrong. Keep using the `v` prefix according to this [doc](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning).
Since we don't have any tooling to create a `CHANGELOG` please also create a release on GitHub with some description about the changes:
<img width="1652" alt="Screenshot 2024-04-03 at 08 58 13" src="https://github.com/shiftcode/github-action-skip/assets/8394182/abd81a9b-9b3c-442e-a083-57d0549242dc">

When the release is done create a PR with using the new skip version in https://github.com/shiftcode/sc-commons-public/blob/main/.github/workflows/main.yml.

2024-04-03 07:00 UTC, michaelwittwer commented
@vitaliibendyk please check the build which is currently failing.

2024-04-04 09:47 UTC, michaelwittwer requested changes

2024-04-04 09:47 UTC, michaelwittwer commented on .github/workflows/test.yml
> +            # allow packages inside this repo to consume from our private npm registry
@vitaliibendyk check indent here, since this comment is for the next line it should start at the same indent

2024-04-04 09:47 UTC, michaelwittwer commented on dist/package.json
@vitaliibendyk did you find a way to omit this being in the source?

2024-04-04 10:07 UTC, michaelwittwer approved these changes

2024-04-04 10:08 UTC, merged